### ISSUE TITLE
Создание архитектуры проекта

### ISSUE THREAD

**Issue by cyberAndrey** [VladmirV/AR_Dev#2]
Спроектировать будущее приложение с помощью методологии IDEF

Диаграммы загрузить на Google Диск и оставить здесь ссылку

**Comment by VladmirV** [comment]
Созданы следующие диаграммы:
- Общая диаграмма архитектуры проекта
- Use-Case диаграмма
[Ссылка](https://app.diagrams.net/#G1epfxkTxDlMF41Qh8eLFBoD1Tj6jwt7wK) на диаграммы.
